<Type Name="UnhandledExceptionAction" FullName="System.Activities.UnhandledExceptionAction">
  <Metadata><Meta Name="ms.openlocfilehash" Value="eb5bf38c7ceaf3497674d9c7512dd5e4aea25746" /><Meta Name="ms.sourcegitcommit" Value="0084afad1b3b1cb2c8ad2c142ae3597d08bad4a7" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="ja-JP" /><Meta Name="ms.lasthandoff" Value="10/31/2019" /><Meta Name="ms.locfileid" Value="73376253" /></Metadata><TypeSignature Language="C#" Value="public enum UnhandledExceptionAction" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed UnhandledExceptionAction extends System.Enum" />
  <TypeSignature Language="DocId" Value="T:System.Activities.UnhandledExceptionAction" />
  <TypeSignature Language="VB.NET" Value="Public Enum UnhandledExceptionAction" />
  <TypeSignature Language="C++ CLI" Value="public enum class UnhandledExceptionAction" />
  <TypeSignature Language="F#" Value="type UnhandledExceptionAction = " />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary><span data-ttu-id="e18b2-101">例外がワークフローのルートをエスケープするときに発生するアクションを指定します。</span><span class="sxs-lookup"><span data-stu-id="e18b2-101">Specifies the action that occurs when an exception escapes the root of a workflow.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="e18b2-102">例外がワークフローのルートをエスケープすると、<xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 関数が呼び出されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-102">The <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> function is invoked if an exception escapes the root of the workflow.</span></span> <span data-ttu-id="e18b2-103"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> は、例外へのアクセス、および例外を生成した <xref:System.Activities.Activity> へのポインターを提供します。</span><span class="sxs-lookup"><span data-stu-id="e18b2-103">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> provides access to the exception as well as a pointer to the <xref:System.Activities.Activity> that generated the exception.</span></span> <span data-ttu-id="e18b2-104">Terminate は、<xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> ハンドラーが指定されていない場合の既定のアクションです。</span><span class="sxs-lookup"><span data-stu-id="e18b2-104">Terminate is the default action if no <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is specified.</span></span>  
  
   
  
## Examples

<span data-ttu-id="e18b2-105">次の例では、例外をスローするワークフローを呼び出しています。</span><span class="sxs-lookup"><span data-stu-id="e18b2-105">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="e18b2-106">ワークフローで例外が処理されないため、<xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> ハンドラーが呼び出されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-106">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="e18b2-107">例外に関する情報を提供するために <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> が調査され、ワークフローは終了します。</span><span class="sxs-lookup"><span data-stu-id="e18b2-107">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
[!code-csharp[CFX_WorkflowApplicationExample#6](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#6)]  

<span data-ttu-id="e18b2-108">次の例では、例外をスローするワークフローを呼び出しています。</span><span class="sxs-lookup"><span data-stu-id="e18b2-108">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="e18b2-109">ワークフローで例外が処理されないため、<xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> ハンドラーが呼び出されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-109">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="e18b2-110">例外に関する情報を提供するために <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> が調査され、ワークフローは中止されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-110">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is aborted.</span></span>  
  
[!code-csharp[CFX_WorkflowApplicationExample#7](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#7)]  

<span data-ttu-id="e18b2-111">次の例では、例外をスローするワークフローを呼び出しています。</span><span class="sxs-lookup"><span data-stu-id="e18b2-111">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="e18b2-112">ワークフローで例外が処理されないため、<xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> ハンドラーが呼び出されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-112">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="e18b2-113">例外に関する情報を提供するために <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> が調査され、ワークフローはキャンセルされます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-113">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is cancelled.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#8](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#8)]  

 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="Abort">
      <MemberSignature Language="C#" Value="Abort" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Abort = int32(0)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Abort" />
      <MemberSignature Language="VB.NET" Value="Abort" />
      <MemberSignature Language="C++ CLI" Value="Abort" />
      <MemberSignature Language="F#" Value="Abort = 0" Usage="System.Activities.UnhandledExceptionAction.Abort" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>0</MemberValue>
      <Docs>
        <summary><span data-ttu-id="e18b2-114"><see cref="T:System.Activities.WorkflowApplication" /> がワークフローを中止するよう指定します。</span><span class="sxs-lookup"><span data-stu-id="e18b2-114">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should abort the workflow.</span></span> <span data-ttu-id="e18b2-115">これにより、中止プロセスの完了時に、<see cref="P:System.Activities.WorkflowApplication.Aborted" /> によって返されたデリゲートが呼び出されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-115">This results in the calling the delegate returned by the <see cref="P:System.Activities.WorkflowApplication.Aborted" /> bwhen the abort process is complete.</span></span> <span data-ttu-id="e18b2-116">中止の理由として未処理の例外が使用されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-116">The unhandled exception is used as the abort reason.</span></span></summary>
      </Docs>
    </Member>
    <Member MemberName="Cancel">
      <MemberSignature Language="C#" Value="Cancel" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Cancel = int32(1)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Cancel" />
      <MemberSignature Language="VB.NET" Value="Cancel" />
      <MemberSignature Language="C++ CLI" Value="Cancel" />
      <MemberSignature Language="F#" Value="Cancel = 1" Usage="System.Activities.UnhandledExceptionAction.Cancel" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>1</MemberValue>
      <Docs>
        <summary><span data-ttu-id="e18b2-117"><see cref="T:System.Activities.WorkflowApplication" /> がルート アクティビティの取り消しをスケジュールして実行を再開するよう指定します。</span><span class="sxs-lookup"><span data-stu-id="e18b2-117">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule the cancellation of the root activity and resume execution.</span></span> <span data-ttu-id="e18b2-118">これにより、キャンセル プロセスの完了時に、<see cref="P:System.Activities.WorkflowApplication.Completed" /> プロパティによって返されたデリゲートが呼び出されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-118">This results in a call to the delegate returned by the <see cref="P:System.Activities.WorkflowApplication.Completed" /> property when the cancellation process is complete.</span></span></summary>
      </Docs>
    </Member>
    <Member MemberName="Terminate">
      <MemberSignature Language="C#" Value="Terminate" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Terminate = int32(2)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Terminate" />
      <MemberSignature Language="VB.NET" Value="Terminate" />
      <MemberSignature Language="C++ CLI" Value="Terminate" />
      <MemberSignature Language="F#" Value="Terminate = 2" Usage="System.Activities.UnhandledExceptionAction.Terminate" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>2</MemberValue>
      <Docs>
        <summary><span data-ttu-id="e18b2-119"><see cref="T:System.Activities.WorkflowApplication" /> がルート アクティビティの終了をスケジュールして実行を再開するよう指定します。</span><span class="sxs-lookup"><span data-stu-id="e18b2-119">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule termination of the root activity and resume execution.</span></span> <span data-ttu-id="e18b2-120">これにより、終了プロセスの完了時に、<see cref="P:System.Activities.WorkflowApplication.Completed" /> プロパティに割り当てられたデリゲートが呼び出されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-120">This results in a call to the delegate assigned to the <see cref="P:System.Activities.WorkflowApplication.Completed" />property when the termination process is complete.</span></span> <span data-ttu-id="e18b2-121">終了の理由として未処理の例外が使用されます。</span><span class="sxs-lookup"><span data-stu-id="e18b2-121">The unhandled exception is used as the termination reason.</span></span> <span data-ttu-id="e18b2-122"><see langword="Terminate" /> ハンドラーが指定されない場合は、<see cref="P:System.Activities.WorkflowApplication.OnUnhandledException" /> が既定のアクションになります。</span><span class="sxs-lookup"><span data-stu-id="e18b2-122"><see langword="Terminate" /> is the default action if no <see cref="P:System.Activities.WorkflowApplication.OnUnhandledException" /> handler is specified.</span></span></summary>
      </Docs>
    </Member>
  </Members>
</Type>
